version: 2

# Custom task removes unnecessary build files before uploading release directory
before_store_artifacts: &before_store_artifacts
  name: Preparing for artifact upload
  command: rm -rf release/*-unpacked release/mac

include_restore_cache: &include_restore_cache
  keys:
    - v1-deps-{{ checksum "yarn.lock" }}
    - v1-deps-

include_save_cache: &include_save_cache
  paths:
    - node_modules
  key: v1-deps-{{ checksum "yarn.lock" }}


jobs:
  build:
    docker:
      - image: electronuserland/builder:10
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          <<: *include_restore_cache

      - run: yarn install

      - run: yarn release --linux

      - save_cache:
          <<: *include_save_cache

      - run:
          <<: *before_store_artifacts

      - store_artifacts:
          path: release/

  build-win:
    docker:
      - image: electronuserland/builder:wine
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          <<: *include_restore_cache

      - run: yarn install

      - run: yarn release --win

      - save_cache:
          <<: *include_save_cache

      - run:
          <<: *before_store_artifacts

      - store_artifacts:
          path: release/

  build-mac:
    macos:
      xcode: '9.0'
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          <<: *include_restore_cache

      - run: yarn install

      - run: yarn release --mac

      - save_cache:
          <<: *include_save_cache

      - run:
          <<: *before_store_artifacts
        
      - store_artifacts:
          path: release/

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build-mac
      - build-win
