version: 2
jobs:
  build:
    docker:
      - image: electronuserland/electron-builder:wine

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - run: yarn run env-cmd .env build --windows
      - run: yarn run env-cmd .env build --linux

      - store_artifacts:
          path: release/

  build-mac:
    macos:
      xcode: '9.0'
    working_directory: ~/repo
    steps:
      - checkout

      - run: yarn install

      - run: yarn run env-cmd .env build --mac

      - store_artifacts:
          path: release/

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - build-mac
